// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Valplas.Data;

#nullable disable

namespace ValplasApi.Migrations
{
    [DbContext(typeof(ValplasContext))]
    [Migration("20241016204334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Valplas.Models.ClientModel", b =>
                {
                    b.Property<Guid>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientAlternativePhone")
                        .HasColumnType("text");

                    b.Property<string>("ClientCUIT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ClientDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientFont")
                        .HasColumnType("text");

                    b.Property<string>("ClientLocality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("ClientNumber")
                        .HasColumnType("numeric");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ClientPointId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientSurname")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ClientTaxCondition")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientType")
                        .HasColumnType("integer");

                    b.Property<string>("ClientWorkingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClientID");

                    b.HasIndex("ClientPointId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Valplas.Models.GeoPointModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Geopoints");
                });

            modelBuilder.Entity("Valplas.Models.ClientModel", b =>
                {
                    b.HasOne("Valplas.Models.GeoPointModel", "ClientPoint")
                        .WithMany()
                        .HasForeignKey("ClientPointId");

                    b.Navigation("ClientPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
